spring:
  application:
    name: gayya-notification-scheduler

logging:
  level:
    root: INFO
    org.ajaxer: DEBUG

---
firebase.collection-prefix: "test_"

---
android:
  notification:
    channel-id: "DailyReminderChannel"